# This is a basic workflow to help you get started with Actions

name: deploy-prod

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request:
    paths:
     - 'bicep-deploy/**'
    types: [opened, reopened, edited, synchronize]
    branches:    
      - 'main'
  push:
    paths:
     - 'bicep-deploy/**'
    branches:    
      - 'main'
permissions:
      id-token: write
      contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Bicep-Whatif-OR-Create:
    name: Bicep Whatif or Create
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Run What-if using ARM deploy
      uses: azure/arm-deploy@v1
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'  }}
      with:
        template: ./bicep-deploy/main.bicep
        parameters: ./bicep-deploy/main.bicepparam
        scope: managementgroup
        managementGroupId: rlab
        additionalArguments: "--what-if"
        region: westeurope
        deploymentName: deploy-bicep-sandbox-01-sp
        
    - name: Deployment using ARM deploy
      uses: azure/arm-deploy@v1
      if: ${{ github.event_name == 'push' }}
      with:
        template: ./bicep-deploy/main.bicep
        parameters: ./bicep-deploy/main.bicepparam
        scope: managementgroup
        managementGroupId: rlab
        region: westeurope
        deploymentName: deploy-bicep-sandbox-01-sp
